<a href="https://colab.research.google.com/github/bajrang2879/bajrangybifoundationproject/blob/main/ybifoundationproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

Open In Colab

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
Import Data
from sklearn.datasets import load_digits
df = load_digits()
_, axes = plt.subplots(nrows = 1, ncols = 4, figsize = (10, 3))
for ax, image, label in zip(axes, df.images, df.target):
    ax.set_axis_off()
    ax.imshow(image, cmap=plt.cm.gray_r, interpolation = 'nearest')
    ax.set_title('Training: %i' % label)

Data Preprocessing
Flatten Image
df.images.shape
(1797, 8, 8)
df.images[0]
array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])
df.images[0].shape
(8, 8)
n_samples = len(df.images)
data = df.images.reshape((n_samples, -1))
data[0]
array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])
data[0].shape
(64,)
data.shape
(1797, 64)
Scaling Data
data.min()
0.0
data.max()
16.0
data = data/16
data.min()
0.0
data.max()
1.0
data[0]
array([0.    , 0.    , 0.3125, 0.8125, 0.5625, 0.0625, 0.    , 0.    ,
       0.    , 0.    , 0.8125, 0.9375, 0.625 , 0.9375, 0.3125, 0.    ,
       0.    , 0.1875, 0.9375, 0.125 , 0.    , 0.6875, 0.5   , 0.    ,
       0.    , 0.25  , 0.75  , 0.    , 0.    , 0.5   , 0.5   , 0.    ,
       0.    , 0.3125, 0.5   , 0.    , 0.    , 0.5625, 0.5   , 0.    ,
       0.    , 0.25  , 0.6875, 0.    , 0.0625, 0.75  , 0.4375, 0.    ,
       0.    , 0.125 , 0.875 , 0.3125, 0.625 , 0.75  , 0.    , 0.    ,
       0.    , 0.    , 0.375 , 0.8125, 0.625 , 0.    , 0.    , 0.    ])
Train test split Data
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(data, df.target, test_size = 0.3)
xtrain.shape, xtest.shape, ytrain.shape, ytest.shape
((1257, 64), (540, 64), (1257,), (540,))
Random Forest model
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(xtrain, ytrain)
RandomForestClassifier()
Predict Test Data
y_pred = rf.predict(xtest)
y_pred
array([2, 6, 1, 1, 8, 6, 7, 7, 3, 1, 1, 8, 6, 7, 1, 7, 6, 6, 6, 3, 8, 9,
       9, 2, 8, 0, 6, 8, 0, 4, 5, 1, 7, 5, 7, 2, 4, 8, 9, 9, 9, 8, 5, 0,
       9, 0, 1, 6, 5, 5, 5, 3, 2, 7, 3, 3, 7, 2, 1, 4, 2, 4, 7, 0, 6, 6,
       7, 2, 5, 4, 6, 7, 5, 1, 2, 5, 8, 6, 3, 6, 6, 2, 8, 0, 1, 0, 2, 7,
       0, 4, 5, 3, 3, 8, 3, 3, 0, 5, 5, 5, 4, 2, 8, 0, 8, 2, 4, 6, 1, 9,
       4, 7, 9, 7, 7, 3, 5, 6, 1, 3, 5, 4, 7, 9, 1, 1, 9, 8, 7, 6, 3, 5,
       4, 4, 5, 7, 6, 7, 9, 0, 9, 8, 7, 4, 9, 9, 7, 8, 7, 5, 9, 4, 8, 6,
       2, 8, 4, 6, 3, 8, 4, 1, 7, 5, 3, 7, 0, 7, 8, 8, 1, 6, 9, 4, 8, 6,
       9, 4, 3, 4, 5, 7, 9, 2, 6, 1, 9, 6, 2, 5, 8, 3, 6, 6, 4, 3, 1, 7,
       2, 4, 7, 6, 3, 5, 6, 4, 9, 6, 2, 8, 9, 2, 5, 6, 3, 3, 2, 8, 6, 9,
       0, 9, 1, 7, 5, 0, 7, 5, 7, 8, 8, 3, 8, 7, 7, 2, 5, 8, 1, 4, 8, 5,
       7, 1, 8, 9, 6, 0, 7, 4, 4, 4, 7, 8, 8, 2, 9, 4, 2, 4, 8, 3, 9, 4,
       4, 7, 7, 9, 6, 6, 7, 4, 9, 7, 6, 0, 0, 1, 8, 1, 7, 1, 9, 4, 8, 8,
       7, 3, 7, 2, 0, 3, 4, 9, 2, 3, 5, 2, 6, 2, 4, 5, 9, 5, 0, 3, 7, 6,
       7, 5, 5, 7, 7, 3, 0, 1, 3, 5, 2, 1, 9, 0, 0, 8, 9, 8, 6, 1, 0, 6,
       9, 1, 1, 4, 2, 5, 1, 9, 7, 9, 2, 2, 3, 4, 3, 0, 5, 1, 5, 0, 6, 6,
       6, 8, 0, 8, 6, 2, 8, 2, 1, 2, 8, 5, 3, 0, 7, 3, 6, 1, 3, 9, 8, 5,
       9, 0, 2, 4, 4, 9, 1, 5, 7, 0, 8, 9, 8, 5, 6, 8, 2, 8, 1, 0, 2, 1,
       1, 0, 3, 5, 5, 9, 8, 9, 4, 3, 2, 3, 4, 6, 8, 4, 3, 8, 8, 1, 3, 8,
       9, 8, 9, 0, 2, 3, 1, 0, 0, 5, 9, 2, 4, 7, 2, 7, 7, 3, 8, 2, 8, 0,
       3, 6, 9, 4, 7, 6, 9, 6, 9, 6, 1, 0, 9, 8, 0, 2, 9, 2, 5, 2, 5, 8,
       0, 6, 6, 7, 7, 8, 2, 2, 2, 1, 8, 3, 2, 7, 4, 4, 6, 9, 4, 6, 9, 7,
       2, 0, 1, 9, 4, 7, 5, 0, 9, 8, 1, 1, 0, 1, 8, 3, 7, 9, 6, 7, 9, 9,
       0, 7, 1, 9, 0, 6, 6, 4, 5, 1, 8, 3, 6, 0, 8, 4, 0, 7, 4, 7, 5, 5,
       7, 2, 8, 6, 1, 7, 0, 5, 0, 9, 6, 6])
Model Accuracy
from sklearn.metrics import confusion_matrix, classification_report
confusion_matrix(ytest, y_pred)
array([[47,  0,  0,  0,  2,  0,  0,  0,  0,  0],
       [ 0, 46,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 50,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 43,  0,  1,  0,  3,  2,  0],
       [ 0,  0,  0,  0, 48,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0, 49,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0, 61,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 60,  0,  0],
       [ 0,  1,  0,  1,  0,  0,  0,  1, 61,  0],
       [ 0,  0,  0,  1,  0,  0,  0,  1,  1, 59]], dtype=int64)
print(classification_report(ytest, y_pred))
              precision    recall  f1-score   support

           0       1.00      0.96      0.98        49
           1       0.96      1.00      0.98        46
           2       1.00      1.00      1.00        50
           3       0.96      0.88      0.91        49
           4       0.96      0.98      0.97        49
           5       0.98      1.00      0.99        49
           6       1.00      0.98      0.99        62
           7       0.91      1.00      0.95        60
           8       0.95      0.95      0.95        64
           9       1.00      0.95      0.98        62

    accuracy                           0.97       540
   macro avg       0.97      0.97      0.97       540
weighted avg       0.97      0.97      0.97       540



  File "<tokenize>", line 113
    0       1.00      0.96      0.98        49
    ^
IndentationError: unindent does not match any outer indentation level

IndentationError: ignored